name: Run presubmit checks

on:
  pull_request:
    branches: [main, staging, dev]
  push:
    branches: [main, staging, dev]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Crash Web
        run: |
          npm ci
          npm run lint:check-eslint
          npm run lint:check-prettier
          npm test
          npm run build
